### ISSUE TITLE
Decide on a name for sshkit.ex

### ISSUE THREAD

**Issue by tessi** [bitcrowd/warp#1]
We should collect and decide on a name for the ssh-wrapper.

The current list of names consists of:

* sshkit.ex
* sshkit (without `.ex`)
* liSSHard
* sshwrap

**Comment by tessi** [comment]
I, personally, like the current name. I'd vote to just take sshkit.ex. But I don't feel too strong about this.

**Comment by xhr15** [comment]
I would agree. It kind of tells you what it does

**Comment by tessi** [comment]
Let me cite hex.pm for tips on name finding:

> Naming your package
> Before publishing, you will have to choose the name of your package. Remember that packages published to Hex are public and can be accessed by anyone in the community. It is also the responsibility of the community to pick and encourage good package names. Here are some tips:
> 
> Avoid using offensive or harassing package names, nicknames, or other identifiers that might detract from a friendly, safe, and welcoming environment for all.
If you are providing functionality on top of an existing package, consider using that package name as a prefix. For example, if you want to add authentication to Plug, consider calling your package plug_auth (or plug_somename) instead of auth (or somename).
Avoid namespace conflicts with existing packages. Plug owns the Plug namespace, if you have an authentication package for Plug use the namespace PlugAuth instead of Plug.Auth.
With a name in hand, it is time to add the proper metadata to your mix.exs file.

It seems that a dot (`.`) separates namespaces. So the name `sshkit.ex` suggests that we live in the `sshkit` namespace and have a `ex` app in there. That is not entirely true and might speak against using the `sshkit.ex` name

**Comment by tessi** [comment]
**liSSHard** ( like lizard just for SSH)

![](http://animal-dream.com/data_images/lizard/lizard4.jpg)

**Comment by tessi** [comment]
it's sshkit (and the repo will be named sshkit.ex) -- voted offline
